name: mis_app
description: "Mobile Information Systems Project"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_messaging: ^15.2.0
  provider: ^6.1.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
