// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0wmKozofU9I68N5Skrkr6ikkpNDbsDZY',
    appId: '1:750028069680:web:22ad9522cf2069f5da86f5',
    messagingSenderId: '750028069680',
    projectId: 'misapp-4e6ca',
    authDomain: 'misapp-4e6ca.firebaseapp.com',
    storageBucket: 'misapp-4e6ca.firebasestorage.app',
    measurementId: 'G-BM38XEG27F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuh_B-c7Nrgb4moS148jpWx0iws_qx8KI',
    appId: '1:750028069680:android:04580a327bbafa0ada86f5',
    messagingSenderId: '750028069680',
    projectId: 'misapp-4e6ca',
    storageBucket: 'misapp-4e6ca.firebasestorage.app',
  );
}
